platform :ios, '11.0'

target 'driverApp' do

  plugin 'cocoapods-art', :sources => [
    'ios-keycore'
  ]
  source 'https://github.com/CocoaPods/Specs.git'

  # ignore all warnings from all pods
  inhibit_all_warnings!

  # RN pods
  # http://facebook.github.io/react-native/docs/integration-with-existing-apps.htm
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-sensitive-info', :path => '../node_modules/react-native-sensitive-info'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'OTASDK', '~> 3.11.2'
  pod 'Stripe', '~> 13.2.0'
  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
    'FaceDetector'
  ]
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  
  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end
