
platform :ios, '11.0'

target 'driverApp' do

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	plugin 'cocoapods-art', :sources => [ 'ios-keycore'
	]
	source 'https://github.com/CocoaPods/Specs.git'

  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for driverApp
	pod 'OTASDK'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'react-native-sensitive-info', :path => '../node_modules/react-native-sensitive-info'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNImageRotate', :path => '../node_modules/react-native-image-rotate'

end
